version: "3"

__feature_db_start__
volumes:
    db_data:
__feature_db_end__

services:
    web:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../html:/www
            - ./data/logs:/logs
        links:
            - server
        networks:
            - network

    server:
        build:
            context: .
            dockerfile: Dockerfile
        stop_grace_period: 0s
        environment:
            PORT: __app_server_port__

            __feature_db_start__
            DATABASE: __app_db_name__
            DATABASE_USER: __app_db_user__
            DATABASE_PASSWORD: __app_db_password__
            __feature_db_end__

        volumes:
            - ./data:/data
            - ../:/app
        __feature_db_start__
        links:
            - db
        depends_on:
            db:
                condition: service_healthy
        __feature_db_end__
        networks:
            - network

    __feature_db_start__
    db:
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_DB: __app_db_name__
            POSTGRES_USER: __app_db_user__
            POSTGRES_PASSWORD: __app_db_password__
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U __app_db_user__ -d __app_db_name__"]
            interval: 1s
            timeout: 5s
            retries: 5
    __feature_db_end__

networks:
    network:
        driver: bridge
