version: "3"
services:
    web:
        environment:
            VIRTUAL_HOST: __app_host_list__
            LETSENCRYPT_HOST: __app_host_list__
            LETSENCRYPT_EMAIL: __app_email__
        networks:
            - reverse_proxy
networks:
    reverse_proxy:
        external:
            name: nginx-proxy
